// Shared language definitions with codes, flags, display names, and default values
const SUPPORTED_LANGUAGES = {
  en: {
    flag: "🇬🇧",
    displayName: "English",
    defaults: {
      "meta.locale": "en_US",
      "meta.language": "English",
      "nav.about": "About",
      "nav.gallery": "Gallery",
      "nav.reviews": "Reviews",
      "nav.location": "Location",
      "badges.superhost": "Superhost",
      "badges.guest_favorite": "Guest Favorite",
      "hero.cta": "Check Availability",
      "amenities.title": "Amenities",
      "reviews.title": "What Our Guests Say",
      "reviews.read_all": "Read All Reviews on Airbnb",
    },
  },
  fr: {
    flag: "🇫🇷",
    displayName: "Français",
    defaults: {
      "meta.locale": "fr_FR",
      "meta.language": "Français",
      "nav.about": "À propos",
      "nav.gallery": "Galerie",
      "nav.reviews": "Avis",
      "nav.location": "Emplacement",
      "badges.superhost": "Superhost",
      "badges.guest_favorite": "Favori des voyageurs",
      "hero.cta": "Vérifier la disponibilité",
      "amenities.title": "Équipements",
      "reviews.title": "Ce que disent nos voyageurs",
      "reviews.read_all": "Lire tous les avis sur Airbnb",
    },
  },
  sv: {
    flag: "🇸🇪",
    displayName: "Svenska",
    defaults: {
      "meta.locale": "sv_SE",
      "meta.language": "Svenska",
      "nav.about": "Om",
      "nav.gallery": "Galleri",
      "nav.reviews": "Recensioner",
      "nav.location": "Plats",
      "badges.superhost": "Superhost",
      "badges.guest_favorite": "Gästfavorit",
      "hero.cta": "Kontrollera tillgänglighet",
      "amenities.title": "Bekvämligheter",
      "reviews.title": "Vad våra gäster säger",
      "reviews.read_all": "Läs alla recensioner på Airbnb",
    },
  },
  de: {
    flag: "🇩🇪",
    displayName: "Deutsch",
    defaults: {
      "meta.locale": "de_DE",
      "meta.language": "Deutsch",
      "nav.about": "Über",
      "nav.gallery": "Galerie",
      "nav.reviews": "Bewertungen",
      "nav.location": "Standort",
      "badges.superhost": "Superhost",
      "badges.guest_favorite": "Gastliebling",
      "hero.cta": "Verfügbarkeit prüfen",
      "amenities.title": "Ausstattung",
      "reviews.title": "Was unsere Gäste sagen",
      "reviews.read_all": "Alle Bewertungen auf Airbnb lesen",
    },
  },
  es: {
    flag: "🇪🇸",
    displayName: "Español",
    defaults: {
      "meta.locale": "es_ES",
      "meta.language": "Español",
      "nav.about": "Acerca de",
      "nav.gallery": "Galería",
      "nav.reviews": "Reseñas",
      "nav.location": "Ubicación",
      "badges.superhost": "Superhost",
      "badges.guest_favorite": "Favorito de los huéspedes",
      "hero.cta": "Verificar disponibilidad",
      "amenities.title": "Servicios",
      "reviews.title": "Lo que dicen nuestros huéspedes",
      "reviews.read_all": "Leer todas las reseñas en Airbnb",
    },
  },
  it: {
    flag: "🇮🇹",
    displayName: "Italiano",
    defaults: {
      "meta.locale": "it_IT",
      "meta.language": "Italiano",
      "nav.about": "Chi siamo",
      "nav.gallery": "Galleria",
      "nav.reviews": "Recensioni",
      "nav.location": "Posizione",
      "badges.superhost": "Superhost",
      "badges.guest_favorite": "Preferito dagli ospiti",
      "hero.cta": "Verifica disponibilità",
      "amenities.title": "Servizi",
      "reviews.title": "Cosa dicono i nostri ospiti",
      "reviews.read_all": "Leggi tutte le recensioni su Airbnb",
    },
  },
  pt: {
    flag: "🇵🇹",
    displayName: "Português",
    defaults: {
      "meta.locale": "pt_PT",
      "meta.language": "Português",
      "nav.about": "Sobre",
      "nav.gallery": "Galeria",
      "nav.reviews": "Avaliações",
      "nav.location": "Localização",
      "badges.superhost": "Superhost",
      "badges.guest_favorite": "Favorito dos hóspedes",
      "hero.cta": "Verificar disponibilidade",
      "amenities.title": "Comodidades",
      "reviews.title": "O que nossos hóspedes dizem",
      "reviews.read_all": "Ler todas as avaliações no Airbnb",
    },
  },
  nl: {
    flag: "🇳🇱",
    displayName: "Nederlands",
    defaults: {
      "meta.locale": "nl_NL",
      "meta.language": "Nederlands",
      "nav.about": "Over",
      "nav.gallery": "Galerij",
      "nav.reviews": "Beoordelingen",
      "nav.location": "Locatie",
      "badges.superhost": "Superhost",
      "badges.guest_favorite": "Gastfavoriet",
      "hero.cta": "Beschikbaarheid controleren",
      "amenities.title": "Voorzieningen",
      "reviews.title": "Wat onze gasten zeggen",
      "reviews.read_all": "Alle beoordelingen op Airbnb lezen",
    },
  },
  da: {
    flag: "🇩🇰",
    displayName: "Dansk",
    defaults: {
      "meta.locale": "da_DK",
      "meta.language": "Dansk",
      "nav.about": "Om",
      "nav.gallery": "Galleri",
      "nav.reviews": "Anmeldelser",
      "nav.location": "Placering",
      "badges.superhost": "Superhost",
      "badges.guest_favorite": "Gæstefavorit",
      "hero.cta": "Tjek tilgængelighed",
      "amenities.title": "Faciliteter",
      "reviews.title": "Hvad vores gæster siger",
      "reviews.read_all": "Læs alle anmeldelser på Airbnb",
    },
  },
  no: {
    flag: "🇳🇴",
    displayName: "Norsk",
    defaults: {
      "meta.locale": "no_NO",
      "meta.language": "Norsk",
      "nav.about": "Om",
      "nav.gallery": "Galleri",
      "nav.reviews": "Anmeldelser",
      "nav.location": "Plassering",
      "badges.superhost": "Superhost",
      "badges.guest_favorite": "Gjeste favoritt",
      "hero.cta": "Sjekk tilgjengelighet",
      "amenities.title": "Fasiliteter",
      "reviews.title": "Hva våre gjester sier",
      "reviews.read_all": "Les alle anmeldelser på Airbnb",
    },
  },
  fi: {
    flag: "🇫🇮",
    displayName: "Suomi",
    defaults: {
      "meta.locale": "fi_FI",
      "meta.language": "Suomi",
      "nav.about": "Tietoja",
      "nav.gallery": "Galleria",
      "nav.reviews": "Arvostelut",
      "nav.location": "Sijainti",
      "badges.superhost": "Superhost",
      "badges.guest_favorite": "Vieras suosikki",
      "hero.cta": "Tarkista saatavuus",
      "amenities.title": "Mukavuuksia",
      "reviews.title": "Mitä vieraamme sanovat",
      "reviews.read_all": "Lue kaikki arvostelut Airbnb:llä",
    },
  },
  pl: {
    flag: "🇵🇱",
    displayName: "Polski",
    defaults: {
      "meta.locale": "pl_PL",
      "meta.language": "Polski",
      "nav.about": "O nas",
      "nav.gallery": "Galeria",
      "nav.reviews": "Recenzje",
      "nav.location": "Lokalizacja",
      "badges.superhost": "Superhost",
      "badges.guest_favorite": "Ulubione gości",
      "hero.cta": "Sprawdź dostępność",
      "amenities.title": "Udogodnienia",
      "reviews.title": "Co mówią nasi goście",
      "reviews.read_all": "Przeczytaj wszystkie recenzje na Airbnb",
    },
  },
  ru: {
    flag: "🇷🇺",
    displayName: "Русский",
    defaults: {
      "meta.locale": "ru_RU",
      "meta.language": "Русский",
      "nav.about": "О нас",
      "nav.gallery": "Галерея",
      "nav.reviews": "Отзывы",
      "nav.location": "Расположение",
      "badges.superhost": "Суперхост",
      "badges.guest_favorite": "Любимец гостей",
      "hero.cta": "Проверить доступность",
      "amenities.title": "Удобства",
      "reviews.title": "Что говорят наши гости",
      "reviews.read_all": "Читать все отзывы на Airbnb",
    },
  },
  ja: {
    flag: "🇯🇵",
    displayName: "日本語",
    defaults: {
      "meta.locale": "ja_JP",
      "meta.language": "日本語",
      "nav.about": "概要",
      "nav.gallery": "ギャラリー",
      "nav.reviews": "レビュー",
      "nav.location": "場所",
      "badges.superhost": "スーパーホスト",
      "badges.guest_favorite": "ゲストのお気に入り",
      "hero.cta": "空き状況を確認",
      "amenities.title": "設備",
      "reviews.title": "ゲストの声",
      "reviews.read_all": "Airbnbで全レビューを読む",
    },
  },
  ko: {
    flag: "🇰🇷",
    displayName: "한국어",
    defaults: {
      "meta.locale": "ko_KR",
      "meta.language": "한국어",
      "nav.about": "소개",
      "nav.gallery": "갤러리",
      "nav.reviews": "후기",
      "nav.location": "위치",
      "badges.superhost": "슈퍼호스트",
      "badges.guest_favorite": "게스트 선호",
      "hero.cta": "예약 가능 여부 확인",
      "amenities.title": "편의시설",
      "reviews.title": "게스트 후기",
      "reviews.read_all": "Airbnb에서 모든 후기 보기",
    },
  },
  zh: {
    flag: "🇨🇳",
    displayName: "中文",
    defaults: {
      "meta.locale": "zh_CN",
      "meta.language": "中文",
      "nav.about": "关于",
      "nav.gallery": "相册",
      "nav.reviews": "评价",
      "nav.location": "位置",
      "badges.superhost": "超赞房东",
      "badges.guest_favorite": "房客最爱",
      "hero.cta": "查看可订状态",
      "amenities.title": "设施",
      "reviews.title": "房客评价",
      "reviews.read_all": "在爱彼迎查看所有评价",
    },
  },
  ar: {
    flag: "🇸🇦",
    displayName: "العربية",
    defaults: {
      "meta.locale": "ar_SA",
      "meta.language": "العربية",
      "nav.about": "حول",
      "nav.gallery": "معرض الصور",
      "nav.reviews": "التقييمات",
      "nav.location": "الموقع",
      "badges.superhost": "مضيف متميز",
      "badges.guest_favorite": "مفضل الضيوف",
      "hero.cta": "تحقق من التوفر",
      "amenities.title": "المرافق",
      "reviews.title": "ماذا يقول ضيوفنا",
      "reviews.read_all": "اقرأ جميع التقييمات على Airbnb",
    },
  },
  hi: {
    flag: "🇮🇳",
    displayName: "हिन्दी",
    defaults: {
      "meta.locale": "hi_IN",
      "meta.language": "हिन्दी",
      "nav.about": "के बारे में",
      "nav.gallery": "गैलरी",
      "nav.reviews": "समीक्षाएं",
      "nav.location": "स्थान",
      "badges.superhost": "सुपरहोस्ट",
      "badges.guest_favorite": "मेहमानों की पसंद",
      "hero.cta": "उपलब्धता जांचें",
      "amenities.title": "सुविधाएं",
      "reviews.title": "हमारे मेहमान क्या कहते हैं",
      "reviews.read_all": "Airbnb पर सभी समीक्षाएं पढ़ें",
    },
  },
  tr: {
    flag: "🇹🇷",
    displayName: "Türkçe",
    defaults: {
      "meta.locale": "tr_TR",
      "meta.language": "Türkçe",
      "nav.about": "Hakkında",
      "nav.gallery": "Galeri",
      "nav.reviews": "Değerlendirmeler",
      "nav.location": "Konum",
      "badges.superhost": "Süper Ev Sahibi",
      "badges.guest_favorite": "Misafir Favorisi",
      "hero.cta": "Müsaitlik kontrolü",
      "amenities.title": "Olanaklar",
      "reviews.title": "Misafirlerimiz ne diyor",
      "reviews.read_all": "Airbnb'deki tüm değerlendirmeleri oku",
    },
  },
  fil: {
    flag: "🇵🇭",
    displayName: "Filipino",
    defaults: {
      "meta.locale": "fil_PH",
      "meta.language": "Filipino",
      "nav.about": "Tungkol",
      "nav.gallery": "Galeriya",
      "nav.reviews": "Mga Review",
      "nav.location": "Lokasyon",
      "badges.superhost": "Superhost",
      "badges.guest_favorite": "Paborito ng mga Bisita",
      "hero.cta": "Tingnan ang Availability",
      "amenities.title": "Mga Amenidad",
      "reviews.title": "Ano ang Sinasabi ng mga Bisita Namin",
      "reviews.read_all": "Basahin ang Lahat ng Review sa Airbnb",
    },
  },
  id: {
    flag: "🇮🇩",
    displayName: "Bahasa Indonesia",
    defaults: {
      "meta.locale": "id_ID",
      "meta.language": "Bahasa Indonesia",
      "nav.about": "Tentang",
      "nav.gallery": "Galeri",
      "nav.reviews": "Ulasan",
      "nav.location": "Lokasi",
      "badges.superhost": "Superhost",
      "badges.guest_favorite": "Favorit Tamu",
      "hero.cta": "Periksa Ketersediaan",
      "amenities.title": "Fasilitas",
      "reviews.title": "Apa Kata Tamu Kami",
      "reviews.read_all": "Baca Semua Ulasan di Airbnb",
    },
  },
  th: {
    flag: "🇹🇭",
    displayName: "ไทย",
    defaults: {
      "meta.locale": "th_TH",
      "meta.language": "ไทย",
      "nav.about": "เกี่ยวกับ",
      "nav.gallery": "แกลเลอรี่",
      "nav.reviews": "รีวิว",
      "nav.location": "ตำแหน่ง",
      "badges.superhost": "ซูเปอร์โฮสต์",
      "badges.guest_favorite": "ที่ชื่นชอบของแขก",
      "hero.cta": "ตรวจสอบความพร้อม",
      "amenities.title": "สิ่งอำนวยความสะดวก",
      "reviews.title": "แขกของเราพูดอะไร",
      "reviews.read_all": "อ่านรีวิวทั้งหมดบน Airbnb",
    },
  },
  vi: {
    flag: "🇻🇳",
    displayName: "Tiếng Việt",
    defaults: {
      "meta.locale": "vi_VN",
      "meta.language": "Tiếng Việt",
      "nav.about": "Về chúng tôi",
      "nav.gallery": "Thư viện ảnh",
      "nav.reviews": "Đánh giá",
      "nav.location": "Vị trí",
      "badges.superhost": "Chủ nhà siêu cấp",
      "badges.guest_favorite": "Yêu thích của khách",
      "hero.cta": "Kiểm tra tình trạng",
      "amenities.title": "Tiện nghi",
      "reviews.title": "Khách của chúng tôi nói gì",
      "reviews.read_all": "Đọc tất cả đánh giá trên Airbnb",
    },
  },
  br: {
    flag: "🇧🇷",
    displayName: "Português (Brasil)",
    defaults: {
      "meta.locale": "pt_BR",
      "meta.language": "Português (Brasil)",
      "nav.about": "Sobre",
      "nav.gallery": "Galeria",
      "nav.reviews": "Avaliações",
      "nav.location": "Localização",
      "badges.superhost": "Superhost",
      "badges.guest_favorite": "Favorito dos hóspedes",
      "hero.cta": "Verificar disponibilidade",
      "amenities.title": "Comodidades",
      "reviews.title": "O que nossos hóspedes dizem",
      "reviews.read_all": "Ler todas as avaliações no Airbnb",
    },
  },
  ms: {
    flag: "🇲🇾",
    displayName: "Bahasa Melayu",
    defaults: {
      "meta.locale": "ms_MY",
      "meta.language": "Bahasa Melayu",
      "nav.about": "Tentang",
      "nav.gallery": "Galeri",
      "nav.reviews": "Ulasan",
      "nav.location": "Lokasi",
      "badges.superhost": "Superhost",
      "badges.guest_favorite": "Kegemaran Tetamu",
      "hero.cta": "Periksa Ketersediaan",
      "amenities.title": "Kemudahan",
      "reviews.title": "Apa Kata Tetamu Kami",
      "reviews.read_all": "Baca Semua Ulasan di Airbnb",
    },
  },
  uk: {
    flag: "🇺🇦",
    displayName: "Українська",
    defaults: {
      "meta.locale": "uk_UA",
      "meta.language": "Українська",
      "nav.about": "Про нас",
      "nav.gallery": "Галерея",
      "nav.reviews": "Відгуки",
      "nav.location": "Розташування",
      "badges.superhost": "Суперхост",
      "badges.guest_favorite": "Улюбленець гостей",
      "hero.cta": "Перевірити доступність",
      "amenities.title": "Зручності",
      "reviews.title": "Що говорять наші гості",
      "reviews.read_all": "Читати всі відгуки на Airbnb",
    },
  },
  sl: {
    flag: "🇸🇮",
    displayName: "Slovenščina",
    defaults: {
      "meta.locale": "sl_SI",
      "meta.language": "Slovenščina",
      "nav.about": "O nas",
      "nav.gallery": "Galerija",
      "nav.reviews": "Ocene",
      "nav.location": "Lokacija",
      "badges.superhost": "Superhost",
      "badges.guest_favorite": "Gostovska priljubljenka",
      "hero.cta": "Preveri razpoložljivost",
      "amenities.title": "Oprema",
      "reviews.title": "Kaj pravijo naši gostje",
      "reviews.read_all": "Preberi vse ocene na Airbnb",
    },
  },
  hr: {
    flag: "🇭🇷",
    displayName: "Hrvatski",
    defaults: {
      "meta.locale": "hr_HR",
      "meta.language": "Hrvatski",
      "nav.about": "O nama",
      "nav.gallery": "Galerija",
      "nav.reviews": "Recenzije",
      "nav.location": "Lokacija",
      "badges.superhost": "Superhost",
      "badges.guest_favorite": "Omiljeni gostiju",
      "hero.cta": "Provjeri dostupnost",
      "amenities.title": "Sadržaji",
      "reviews.title": "Što kažu naši gosti",
      "reviews.read_all": "Pročitaj sve recenzije na Airbnb",
    },
  },
  bg: {
    flag: "🇧🇬",
    displayName: "Български",
    defaults: {
      "meta.locale": "bg_BG",
      "meta.language": "Български",
      "nav.about": "За нас",
      "nav.gallery": "Галерия",
      "nav.reviews": "Отзиви",
      "nav.location": "Местоположение",
      "badges.superhost": "Супердомакин",
      "badges.guest_favorite": "Любимец на гостите",
      "hero.cta": "Провери наличност",
      "amenities.title": "Удобства",
      "reviews.title": "Какво казват нашите гости",
      "reviews.read_all": "Прочети всички отзиви в Airbnb",
    },
  },
  ro: {
    flag: "🇷🇴",
    displayName: "Română",
    defaults: {
      "meta.locale": "ro_RO",
      "meta.language": "Română",
      "nav.about": "Despre noi",
      "nav.gallery": "Galerie",
      "nav.reviews": "Recenzii",
      "nav.location": "Locație",
      "badges.superhost": "Superhost",
      "badges.guest_favorite": "Favoritul oaspeților",
      "hero.cta": "Verifică disponibilitatea",
      "amenities.title": "Facilități",
      "reviews.title": "Ce spun oaspeții noștri",
      "reviews.read_all": "Citește toate recenziile pe Airbnb",
    },
  },
  hu: {
    flag: "🇭🇺",
    displayName: "Magyar",
    defaults: {
      "meta.locale": "hu_HU",
      "meta.language": "Magyar",
      "nav.about": "Rólunk",
      "nav.gallery": "Galéria",
      "nav.reviews": "Értékelések",
      "nav.location": "Helyszín",
      "badges.superhost": "Superhost",
      "badges.guest_favorite": "Vendégek kedvence",
      "hero.cta": "Ellenőrizd a rendelkezésre állást",
      "amenities.title": "Kényelmi szolgáltatások",
      "reviews.title": "Mit mondanak vendégeink",
      "reviews.read_all": "Olvasd el az összes értékelést az Airbnb-n",
    },
  },
  cs: {
    flag: "🇨🇿",
    displayName: "Čeština",
    defaults: {
      "meta.locale": "cs_CZ",
      "meta.language": "Čeština",
      "nav.about": "O nás",
      "nav.gallery": "Galerie",
      "nav.reviews": "Recenze",
      "nav.location": "Umístění",
      "badges.superhost": "Superhost",
      "badges.guest_favorite": "Oblíbené hostů",
      "hero.cta": "Zkontrolovat dostupnost",
      "amenities.title": "Vybavení",
      "reviews.title": "Co říkají naši hosté",
      "reviews.read_all": "Přečíst všechny recenze na Airbnb",
    },
  },
  el: {
    flag: "🇬🇷",
    displayName: "Ελληνικά",
    defaults: {
      "meta.locale": "el_GR",
      "meta.language": "Ελληνικά",
      "nav.about": "Σχετικά με εμάς",
      "nav.gallery": "Γκαλερί",
      "nav.reviews": "Κριτικές",
      "nav.location": "Τοποθεσία",
      "badges.superhost": "Superhost",
      "badges.guest_favorite": "Αγαπημένο των επισκεπτών",
      "hero.cta": "Ελέγξτε τη διαθεσιμότητα",
      "amenities.title": "Παροχές",
      "reviews.title": "Τι λένε οι επισκέπτες μας",
      "reviews.read_all": "Διαβάστε όλες τις κριτικές στο Airbnb",
    },
  },
  bn: {
    flag: "🇧🇩",
    displayName: "বাংলা",
    defaults: {
      "meta.locale": "bn_BD",
      "meta.language": "বাংলা",
      "nav.about": "আমাদের সম্পর্কে",
      "nav.gallery": "গ্যালারি",
      "nav.reviews": "পর্যালোচনা",
      "nav.location": "অবস্থান",
      "badges.superhost": "সুপারহোস্ট",
      "badges.guest_favorite": "অতিথিদের প্রিয়",
      "hero.cta": "উপলব্ধতা পরীক্ষা করুন",
      "amenities.title": "সুবিধা",
      "reviews.title": "আমাদের অতিথিরা কী বলে",
      "reviews.read_all": "Airbnb-এ সব পর্যালোচনা পড়ুন",
    },
  },
  si: {
    flag: "🇱🇰",
    displayName: "සිංහල",
    defaults: {
      "meta.locale": "si_LK",
      "meta.language": "සිංහල",
      "nav.about": "අප ගැන",
      "nav.gallery": "ගැලරිය",
      "nav.reviews": "සමාලෝචන",
      "nav.location": "ස්ථානය",
      "badges.superhost": "සුපර් හෝස්ට්",
      "badges.guest_favorite": "අමුත්තන්ගේ ප්‍රියතම",
      "hero.cta": "පවතින බව පරීක්ෂා කරන්න",
      "amenities.title": "සුවපහසුකම්",
      "reviews.title": "අපගේ අමුත්තෝ කුමක් කියනවාද",
      "reviews.read_all": "Airbnb හි සියලුම සමාලෝචන කියවන්න",
    },
  },
  ur: {
    flag: "🇵🇰",
    displayName: "اردو",
    defaults: {
      "meta.locale": "ur_PK",
      "meta.language": "اردو",
      "nav.about": "ہمارے بارے میں",
      "nav.gallery": "گیلری",
      "nav.reviews": "تبصرے",
      "nav.location": "مقام",
      "badges.superhost": "سپر ہوسٹ",
      "badges.guest_favorite": "مہمانوں کی پسندیدہ",
      "hero.cta": "دستیابی چیک کریں",
      "amenities.title": "سہولیات",
      "reviews.title": "ہمارے مہمان کیا کہتے ہیں",
      "reviews.read_all": "Airbnb پر تمام تبصرے پڑھیں",
    },
  },
  fa: {
    flag: "🇮🇷",
    displayName: "فارسی",
    defaults: {
      "meta.locale": "fa_IR",
      "meta.language": "فارسی",
      "nav.about": "درباره ما",
      "nav.gallery": "گالری",
      "nav.reviews": "نظرات",
      "nav.location": "موقعیت",
      "badges.superhost": "سوپر هاست",
      "badges.guest_favorite": "مورد علاقه مهمانان",
      "hero.cta": "بررسی در دسترس بودن",
      "amenities.title": "امکانات",
      "reviews.title": "مهمانان ما چه می‌گویند",
      "reviews.read_all": "خواندن همه نظرات در Airbnb",
    },
  },
};

module.exports = SUPPORTED_LANGUAGES;
